Mobile and Desktop version for my project
The-Normal-One1/Visit-Ethiopia pull request #1
Opened 2022-10-19 18:37 UTC by The-Normal-One1

**The following lists are done to create the Visit-Ethiopia**

- Created the HTML, CSS, and script files 
- The images were added to the file for the project.
- Linters were added to the project.
- Built both the home page and the about page.
- Created two different screen sizes for the mobile and desktop versions.
- Added links in the menu to the about page.
- Added the logo in the header links to the home page.
- Added the mobile menu for the mobile version.
- The section "Featured speakers" was created dynamically in JavaScript.

**[A link to loom video](https://www.loom.com/share/f9bf8583a3ff4784aaa7f1510140048c)**

2022-10-19 20:42 UTC, tugsem requested changes
Hi @The-Normal-One1 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!
![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights ⭐ 
✅ Good video presentation
✅ No linters error
✅ Github Flow
✅ Readme is fine

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 20:42 UTC, tugsem commented on style.css
> +  }
- [x] While user in mobile menu, the body part seems on top and overflow is on, so the pictures below overflows the menu when user scrolls down. Kindly fix it: 
![image](https://user-images.githubusercontent.com/91486791/196792036-249d971c-ee6e-488d-bb97-a2a97ec2859a.png)

2022-10-19 20:42 UTC, tugsem commented on style.css
> +  }
- [x] In mobile size, your about page has the correct footer but in your home page, footer doesn't seem. Kindly add it.
![image](https://user-images.githubusercontent.com/91486791/196792925-eaba325b-f582-4c28-bc11-11811c1072ee.png)

2022-10-19 20:42 UTC, tugsem commented on style.css
> +  }
- [x] Kindly make card's background transparent, set the right font color and give true spacings vertically. Also, in the image below, you can see the line, it should be centered. This way it would look more professional and match the figma.
![image](https://user-images.githubusercontent.com/91486791/196793804-c073235a-4742-4e96-ade2-0c3ef3fd38e2.png)
figma: 
![image](https://user-images.githubusercontent.com/91486791/196796996-706ee491-fd5e-4ad2-af49-a240c67b9921.png)

2022-10-19 20:42 UTC, tugsem commented on style.css
> +  }
- [x] Please use the same background image, same font color, font weight as figma template. You can make your navbar white to match the design and your logo would look better. Your duty in this capstone is copying the template as much as possible and changing only the context of it.
![image](https://user-images.githubusercontent.com/91486791/196796077-aec1464e-eb24-408a-9c62-1fa1d0620382.png)
![image](https://user-images.githubusercontent.com/91486791/196796140-caf73539-17ef-4875-b486-ab5926a4df37.png)

2022-10-19 20:42 UTC, tugsem commented on style.css
> +@media only screen and (max-width: 767px) {
- [x] You don't need to write media queries here for mobile first implementation. I suggest you to remove it and take the one for desktop size(min-width: 768px) to the bottom.(copy and paste to the bottom) This is more proper way of doing it and it would be better for one who inspects your code.

2022-10-20 08:17 UTC, The-Normal-One1 commented on style.css
> +  }
Added z-index for the images

2022-10-20 08:24 UTC, The-Normal-One1 commented on style.css
> +  }
Added footer in mobile version for the home page

2022-10-20 13:00 UTC, The-Normal-One1 commented on style.css
> +@media only screen and (max-width: 767px) {
Changed the media queries only for the desktop version

2022-10-20 13:00 UTC, The-Normal-One1 commented on style.css
> +  }
Changed the background colors

2022-10-20 13:00 UTC, The-Normal-One1 commented on style.css
> +  }
Added transparent background

2022-10-20 13:35 UTC, zieeco commented on style.css
> +  }
- [ ] This issue is well resolved :heavy_check_mark:

2022-10-20 13:35 UTC, zieeco commented on style.css
> +  }
- [ ] This issue is well resolved :heavy_check_mark:

2022-10-20 13:35 UTC, zieeco commented on style.css
> +  }
- [ ] This issue is well resolved :heavy_check_mark:

2022-10-20 13:49 UTC, zieeco requested changes
Hi @The-Normal-One1,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 13:49 UTC, zieeco commented on style.css
> +  }
- Hey, here's the right color and font size #515151, 16px. kindly update it as this issue is not yet resolved as suggested by the previous reviewer.

2022-10-20 13:49 UTC, zieeco commented on style.css
> +  }
- Here's the correct font-size: 24px. Kindly fix this as the issue is not yet resolved as requested by the previous reviewer.

2022-10-20 13:49 UTC, zieeco commented on style.css
> +  }
- Here's the correct font-size: 16px. Kindly fix this as the issue is not yet resolved as requested by the previous reviewer.

2022-10-20 15:17 UTC, The-Normal-One1 commented
Hi @zieeco
Thanks for your feedback. 
I think it is not necessary to change the  font sizes and font color

2022-10-20 15:33 UTC, ichala approved these changes
Hi @The-Normal-One1    ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Good Design ✔️  


 Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :
_ N/A
**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 15:38 UTC, merged